# Generated by Django 5.2.3 on 2025-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text='Display this category in the main navigation bar', verbose_name='Show in navbar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first. Categories with same order are sorted alphabetically.'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first. Subcategories with same order are sorted alphabetically.'),
        ),
    ]
