# Generated by Django 5.2.3 on 2025-06-26 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_category_show_in_navbar_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category__order', '-order', 'name'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='category',
            name='template_name',
            field=models.CharField(blank=True, help_text="Override default template (e.g., 'navigation/contact.html')", max_length=100, null=True, verbose_name='Custom Template'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Template'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category should be displayed', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The name of the category as displayed to users', max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first. Categories with same order are sorted alphabetically.', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text='Display this category in the main navigation bar', verbose_name='Show in Navigation'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly version of the name (auto-generated if blank)', max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='navigation.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subcategory Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first within the same category', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_category_subcategory_slug'),
        ),
    ]
